#!/usr/bin/env python3
"""
Notification Setup Script for SEP Monitoring Dashboard
This script helps you configure environment variables for email and SMS notifications.
"""

import os
import sys
from pathlib import Path

def create_env_file():
    """Create .env file with user input"""
    
    print("🔧 SEP Monitoring Dashboard - Notification Setup")
    print("=" * 50)
    print()
    
    # Check if .env already exists
    env_path = Path(".env")
    if env_path.exists():
        print("⚠️  .env file already exists!")
        response = input("Do you want to overwrite it? (y/N): ").lower()
        if response != 'y':
            print("Setup cancelled.")
            return
    
    print("📧 EMAIL CONFIGURATION")
    print("-" * 30)
    
    # Email configuration
    smtp_server = input("SMTP Server (default: smtp.gmail.com): ").strip() or "smtp.gmail.com"
    smtp_port = input("SMTP Port (default: 587): ").strip() or "587"
    smtp_username = input("Email Address: ").strip()
    smtp_password = input("App Password (not your regular password): ").strip()
    
    print()
    print("📱 SMS CONFIGURATION (Twilio)")
    print("-" * 30)
    
    # SMS configuration
    twilio_account_sid = input("Twilio Account SID: ").strip()
    twilio_auth_token = input("Twilio Auth Token: ").strip()
    twilio_phone_number = input("Twilio Phone Number: ").strip()
    
    print()
    print("⚙️  APPLICATION CONFIGURATION")
    print("-" * 30)
    
    # App configuration
    backend_host = input("Backend Host (default: localhost): ").strip() or "localhost"
    backend_port = input("Backend Port (default: 8000): ").strip() or "8000"
    frontend_url = input("Frontend URL (default: http://localhost:3000): ").strip() or "http://localhost:3000"
    
    # Create .env content
    env_content = f"""# Notification Service Environment Variables
# Generated by setup_notifications.py

# =============================================================================
# TWILIO SMS CONFIGURATION
# =============================================================================
TWILIO_ACCOUNT_SID={twilio_account_sid}
TWILIO_AUTH_TOKEN={twilio_auth_token}
TWILIO_PHONE_NUMBER={twilio_phone_number}

# =============================================================================
# EMAIL SMTP CONFIGURATION
# =============================================================================
SMTP_SERVER={smtp_server}
SMTP_PORT={smtp_port}
SMTP_USERNAME={smtp_username}
SMTP_PASSWORD={smtp_password}

# =============================================================================
# APPLICATION CONFIGURATION
# =============================================================================
BACKEND_HOST={backend_host}
BACKEND_PORT={backend_port}
FRONTEND_URL={frontend_url}
"""
    
    # Write .env file
    try:
        with open(".env", "w") as f:
            f.write(env_content)
        print("✅ .env file created successfully!")
        print()
        print("📋 NEXT STEPS:")
        print("1. Start the backend server: python app.py")
        print("2. Test notifications in the frontend")
        print("3. Check the notification bell icon in the topbar")
        
    except Exception as e:
        print(f"❌ Error creating .env file: {e}")
        return False
    
    return True

def show_setup_instructions():
    """Show setup instructions for email and SMS"""
    
    print("📚 SETUP INSTRUCTIONS")
    print("=" * 50)
    print()
    
    print("📧 EMAIL SETUP (Gmail)")
    print("-" * 30)
    print("1. Go to your Google Account settings")
    print("2. Navigate to Security > 2-Step Verification")
    print("3. Enable 2-Step Verification if not already enabled")
    print("4. Go to Security > App passwords")
    print("5. Select 'Mail' as the app")
    print("6. Generate a new app password")
    print("7. Use this app password in the setup (not your regular password)")
    print()
    
    print("📱 SMS SETUP (Twilio)")
    print("-" * 30)
    print("1. Go to https://www.twilio.com and sign up")
    print("2. Verify your phone number during signup")
    print("3. Get your Account SID and Auth Token from the Twilio Console")
    print("4. Buy a phone number in the Twilio Console")
    print("5. Use these credentials in the setup")
    print()
    
    print("🔗 Useful Links:")
    print("- Twilio Console: https://console.twilio.com/")
    print("- Google Account: https://myaccount.google.com/security")
    print("- App Passwords: https://myaccount.google.com/apppasswords")
    print()

def main():
    """Main setup function"""
    
    print("🚀 Welcome to SEP Monitoring Dashboard Notification Setup!")
    print()
    
    # Show instructions first
    show_setup_instructions()
    
    # Ask if user wants to proceed
    response = input("Do you have your credentials ready? (Y/n): ").lower()
    if response == 'n':
        print("Please get your credentials and run this script again.")
        return
    
    # Create .env file
    if create_env_file():
        print()
        print("🎉 Setup complete! Your notification system is ready to use.")
    else:
        print()
        print("❌ Setup failed. Please check the error messages above.")

if __name__ == "__main__":
    main()


